### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by emhamel** [timsainb/noisereduce#68] opened 2022-07-04 22:37 UTC
Hello!,

I am trying to use noisereduce's reduce_noise function to clean some audio data.  When I use a GPU (V100), some of the cleaned audio arrays come back as all NaN.  This does not happen when I run the code on CPU.  Any idea of how I might be able to fix this? Thanks!

**Comment by timsainb** [comment] 2022-07-05 00:36
Does this happen with all of your data or just some? Could you try to reproduce the issue in a colab notebook?

**Comment by emhamel** [comment] 2022-07-09 17:44
Only with some data, I'll work on making a colab notebook to reproduce the issue, thanks!

**Comment by timsainb** [comment] 2023-07-14 03:18
Closing since we changed the GPU backend.

**Closed by timsainb** 2023-07-14 03:18 UTC

**Comment by lzk901372** [comment] 2025-09-08 17:08
I still face same the issue. Any updates?
